apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    name: wordpress
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
